server.port=8080
spring.application.name=marketmax-backend

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.default-property-inclusion=non-null

logging.level.com.marketmax=INFO
logging.level.org.springframework.web=WARN

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

marketmax.jwt.secret=${JWT_SECRET}
marketmax.jwt.expiration-ms=${JWT_EXPIRATION_MS}

# --- CONFIGURAÇÃO DO RESEND (VIA API HTTP) ---
resend.api.key=${RESEND_API_KEY}
marketmax.mail.from=${MAIL_FROM}

marketmax.app.base-url=${APP_BASE_URL}
marketmax.reset-token.expiration-minutes=${RESET_TOKEN_EXPIRATION_MINUTES:30}